### ISSUE TITLE
No option to add welcome motd message as parameter

### ISSUE THREAD

**Issue by donpui** [magic-wormhole/magic-wormhole-mailbox-server#32]
There is no option to add welcome motd message via parameter providing message or setting file to load as message.

https://github.com/magic-wormhole/magic-wormhole-mailbox-server/blob/015a745edb92740b42c9d1cc50225064df75fddc/src/wormhole_mailbox_server/server.py#L690

Currently only option is to edit server.py file and include message in it

**Comment by piegamesde** [comment]
IMO the welcome message should not be a configuration option, but modifiable at runtime. This is needed for example to warn users beforehand of server maintenance downtime, or of high load (e.g. ongoing attacks). Having the server restart every time just to change the message is not ideal.

**Comment by donpui** [comment]
Modifiable at runtime file would be good option. However it need to detect changes and update message stored in memory, not just read file with every connection to provide newest message.

**Comment by meejah** [comment]
What's wrong with re-starting the server (to change MotD)? (Clients should just immediately re-connect and all is well).

**Comment by piegamesde** [comment]
I don't think any clients except Python actually implements this feature.

**Comment by meejah** [comment]
No other clients will re-connect? (Note they don't need to journal state to disk like the mailbox does to have the feature)

**Comment by piegamesde** [comment]
The rust client definitely won't. For the Go client I'm not sure, but I had a quick look at the code and did a few greps for keywords that I'd expect to come up in that context ("reconnect", "timeout", "retry", …) and could not find any signs of such an implementation either.

**Comment by meejah** [comment]
The rust client _used_ to re-connect ... why doesn't it any more?

In any case, the general "philosophy" of the code if you will is to be resilient in the face of network instability. Certainly _one_ reason a connection could go away is if the server is re-started, but there are many other reasons. The reference implementation, state-machines and spec should, I believe, make it clear that correct behavior is to re-connect to the mailbox.

Certainly for Dilation to work, clients must know how to re-connect to their mailbox whenever a network connection goes away. So clients that don't already re-connect should be taught how to.

Since everything else in the server is built around having state properly serialized (before network messages go out) special-casing a "live" reload of just this one piece of state is out-of-place.

**Comment by piegamesde** [comment]
> The rust client used to re-connect IIRC ... why doesn't it any more?

The Rust code base has undergone some heavy refactoring, and some parts have been rewritten from scratch multiple times. Since then, it has never been a high enough priority for me to work on the reconnect logic again.
